name: Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'electro-smith/Patcher-Objects'
          path: 'objects'
          ref: 'main'
          token: ${{ secrets.ES_TOKEN }}
      - uses: actions/checkout@v2
        with:
          path: 'frontend'
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Install Dependencies 1
        run: npm i -f
        working-directory: ./frontend
      - name: Install Dependencies 2
        run: ./build.sh
        working-directory: ./objects
      - name: Build
        run: npm run build
        working-directory: ./frontend
      - name: Deploy To Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: deploy
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/dist
